- name: clonar repositorio git neovim
  hosts: localhost
  vars:
    sdk_shell: "$HOME/.sdkman/bin/sdkman-init.sh"

  tasks:
    - name: instalando SDKMAN
      shell: curl -s "https://get.sdkman.io" | bash
      args:
        executable: /bin/bash

    - name: Inicializando SDKMAN
      shell: "source {{ sdk_shell }} && sdk version"

    - name: Instalando GraalVM(GraalVM Community) 24
      shell: "source {{ sdk_shell }} && sdk install java 24.0.2-graalce"

    - name: Instalando Quarkus CLI
      shell: "source {{ sdk_shell }} && sdk install quarkus"

    - name: Instalando Spring Boot CLI
      shell: "source {{ sdk_shell }} && sdk install springboot"
