- name: clonar repositorio git neovim
  hosts: localhost
  tasks:
    - name: instalando linguagens de programação
      package:
        name:
          - gcc
          - gcc-c++
          - clang
          - golang
          - java-latest-openjdk
          - java-latest-openjdk-devel
        state: present
      when: ansible_facts['distribution'] == "Fedora"
