- name: Instalar Fish
  hosts: localhost
  become: yes
  tasks:
    - name: Instalando pacotes necess√°rios para gerar uma chave
      package:
        name:
          - steam
          - gamemoded
          - gamescope
    # - name: baixndo heroic games

