- name: instalando softwares de uso geral
  hosts: localhost
  become: yes
  gather_facts: true
  tasks:
    - name: ativando repositorio atim/lazygit
      command: dnf copr enable atim/lazygit -y

    - name: pacotes
      package:
        name: 
          - btop
          - keepassxc
          - fastfetch
          - foot
          - steam
          - gamemode
          - gamescope
          - lazygit

    - name: ativando servi√ßo foot server para usuario
      command: systemctl --user --now enable foot-server
      become: false

