- name: clonar repositorio git neovim
  hosts: localhost
  become: yes
  tasks:
    - name: instalando nodejs e pnpm com opt "weak.deps = false"
      package:
        name:
          - nodejs
          - pnpm
        state: present
        install_weak_deps: false
      when: ansible_facts['distribution'] == "Fedora"
